language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t punss21/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true punss21/react-test npm test -- --coverage

after_success:
  - docker build -t punss21/multi-client ./client 
  - docker build -t punss21/multi-nginx ./nginx
  - docker build -t punss21/multi-server ./server
  - docker build -t punss21/multi-worker ./worker

  #Login to docker hub to push the images

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push punss21/multi-client
  - docker push punss21/multi-nginx
  - docker push punss21/multi-server
  - docker push punss21/multi-worker

deploy:
  provider: "elasticbeanstalk"
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-867669335535"
  bucket_path: "multi-docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

